---
title: "Publications of My Papers"
---

Toutefois, les ressources collectées par le secteur bancaire sont dominées par les dépôts à vue qui représentent 74,9% du total des dépôts au 31 décembre 2015, alors que les dépôts à terme ne représentent que 12,6% contre 7,1% pour les dépôts à régime spécial.

**Les montants des transferts des migrants sont sur une tendance haussière** sur la période 2010 – 2015. Ils passent de 131,4 milliards de FCFA en 2010 à 278,9 milliards de FCFA en 2015. Ces montants représentent 1,7 % du PIB en 2015 contre 1,5% en 2012.

**L’étude passe en revue la fiscalité des produits d’épargne au Cameroun**, en relevant en particulier les diverses exonérations fiscales dont bénéficient les produits d’épargne bancaire, les valeurs mobilières et les produits d’assurances.

**Dans le cadre de l’examen des entraves à la mobilisation de l’épargne au Cameroun, l’étude a permis d’identifier comme principaux obstacles :**

**la faible diversification des produits d’épargne financière**  due à l’absence de cadres réglementaires incitatifs pour les instruments d’épargne longue tels que les produits d’épargne collective, d’épargne salariale et de retraite complémentaire ;

-   **les déficiences des mécanismes de protection des épargnants** en matière notamment de traitement de difficultés d’établissements de crédit (notamment des EMF), de transparence des contrats et de tarification des services financiers ;

-   **la rémunération inadéquate des produits d’épargne financière** imputable à l’inflation et aux coûts de gestion élevés ;

-    **la faible accessibilité des populations aux services financiers** en rapport avec le faible taux de pénétration des établissements financiers et leur faible couverture géographique du territoire et les frais élevés de gestion des fonds épargnés ;

-   **les limites de l’intermédiation financière** en relation avec les difficultés rencontrées par les établissements de crédit pour orienter les ressources collectées vers le financement des investissements  du fait notamment de la nature courte de l’essentiel de leurs dépôts et de l’absence de garanties des emprunteurs ;

-   **l’impact limité des mesures d’incitations fiscales en faveur de l’épargne longue** sur les comportements des ménages et des entreprises en raison notamment de leur sensibilisation insuffisante sur les avantages procurés, et l’absence parfois de lien entre les incitations et la durée de détention de l’épargne ;

-   **le faible rôle des marchés de capitaux dans la mobilisation de l’épargne** et le financement de l’économie en raison notamment de leurs faibles profondeurs et de la faiblesse de la culture boursière des épargnants ;
